version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    groups:
      web-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      container-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
