<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SqlSimCity.Edge.Connector</RootNamespace>
    <AssemblyName>SqlSimCity.Edge.Connector</AssemblyName>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SqlSimCity.Edge\SqlSimCity.Edge.csproj" />
    <ProjectReference Include="..\SqlSimCity.Domain\SqlSimCity.Domain.csproj" />
    <ProjectReference Include="..\SqlSimCity.Contracts\SqlSimCity.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SqlSimCity.Edge.Tests" />
  </ItemGroup>

</Project>
