"""
SQLSimCity asset kits — self-authored procedural geometry for Blender.

Run this from Blender to regenerate `web/src/assets/*.glb`:

    SIMCITY_OUT = r"<repo>/web/src/assets"
    exec(open(r"<repo>/blender/simcity_kit.py").read())

Or headless:

    blender --background --python blender/simcity_kit.py

Why this file exists
--------------------
The repository is Apache-2.0 and `NOTICE` states it "includes no SimCity assets". Every vertex here is
therefore generated by this script from first principles: no downloaded models, no scanned geometry, no
third-party libraries. Checking the generator in rather than only the `.glb` keeps the art auditable and
reproducible — the same script always produces the same mesh.

Evidence boundary
-----------------
Nothing in this file is a measurement. These are the *shells* of the six civic facilities and the street
furniture that dresses the empty ground. The measured quantities — table footprints, table heights, and
the fill of each facility's units — are drawn by the web app as separate geometry positioned in the slots
`web/src/cityFacilityShells.ts` defines. Changing anything here can change how the city looks and can
never change what it claims.

Naming contract
---------------
Every exported mesh is named `<asset>__<role>`. The web app reads the role suffix to pick a material, so
a mesh must always carry one of: `body`, `trim`, `glass`, `metal`, `trunk`, `leaf`, `water`.

Units and orientation
---------------------
Blender is Z-up; the glTF exporter converts to the Y-up the web app uses. Landmarks are built normalised
to a plot radius of 1.0 so the scene can scale them to whatever plot a facility gets. Scenery is built at
world scale, where one unit is roughly one metre, matching the city's building footprints.
"""

import math
import os

import bmesh
import bpy
from mathutils import Euler, Matrix, Vector

# --------------------------------------------------------------------------------------------------
# Mesh building
# --------------------------------------------------------------------------------------------------

ROLES = ("body", "trim", "glass", "metal", "trunk", "leaf", "water")


def _matrix(loc, scale, rot=None):
    translation = Matrix.Translation(Vector(loc))
    rotation = Euler(rot if rot else (0.0, 0.0, 0.0), "XYZ").to_matrix().to_4x4()
    return translation @ rotation @ Matrix.Diagonal(Vector(scale).to_4d())


class Part:
    """One accumulating mesh. Primitives are appended in local space and welded on `build`."""

    def __init__(self):
        self.bm = bmesh.new()

    def box(self, size, loc=(0, 0, 0), rot=None):
        bmesh.ops.create_cube(self.bm, size=1.0, matrix=_matrix(loc, size, rot))
        return self

    def cyl(self, radius_top, radius_bottom, height, loc=(0, 0, 0), rot=None, segments=16):
        bmesh.ops.create_cone(
            self.bm,
            cap_ends=True,
            cap_tris=False,
            segments=segments,
            radius1=radius_bottom,
            radius2=radius_top,
            depth=height,
            matrix=_matrix(loc, (1, 1, 1), rot),
        )
        return self

    def sphere(self, radius, loc=(0, 0, 0), scale=(1, 1, 1), segments=12, rings=8):
        bmesh.ops.create_uvsphere(
            self.bm,
            u_segments=segments,
            v_segments=rings,
            radius=radius,
            matrix=_matrix(loc, scale),
        )
        return self

    def wedge(self, width, depth, height, loc=(0, 0, 0), rot=None):
        """A triangular prism running along X — the gable and saw-tooth workhorse."""
        hw, hd = width / 2.0, depth / 2.0
        verts = [
            (-hw, -hd, 0.0), (hw, -hd, 0.0), (hw, hd, 0.0), (-hw, hd, 0.0),
            (-hw, 0.0, height), (hw, 0.0, height),
        ]
        faces = [(0, 1, 2, 3), (0, 4, 5, 1), (3, 2, 5, 4), (0, 3, 4), (1, 5, 2)]
        self._polyhedron(verts, faces, loc, rot)
        return self

    def ramp(self, width, depth, height, loc=(0, 0, 0), rot=None):
        """A right-angled prism: flat at -Y, rising to `height` at +Y."""
        hw, hd = width / 2.0, depth / 2.0
        verts = [
            (-hw, -hd, 0.0), (hw, -hd, 0.0), (hw, hd, 0.0), (-hw, hd, 0.0),
            (-hw, hd, height), (hw, hd, height),
        ]
        faces = [(0, 1, 2, 3), (3, 2, 5, 4), (0, 4, 5, 1), (0, 3, 4), (1, 5, 2)]
        self._polyhedron(verts, faces, loc, rot)
        return self

    def frustum(self, bottom, top, height, loc=(0, 0, 0), rot=None):
        """A rectangular frustum — plinths, mansards, tapered crowns."""
        bx, by = bottom[0] / 2.0, bottom[1] / 2.0
        tx, ty = top[0] / 2.0, top[1] / 2.0
        verts = [
            (-bx, -by, 0.0), (bx, -by, 0.0), (bx, by, 0.0), (-bx, by, 0.0),
            (-tx, -ty, height), (tx, -ty, height), (tx, ty, height), (-tx, ty, height),
        ]
        faces = [(0, 1, 2, 3), (4, 5, 6, 7), (0, 4, 5, 1), (1, 5, 6, 2), (2, 6, 7, 3), (3, 7, 4, 0)]
        self._polyhedron(verts, faces, loc, rot)
        return self

    def arch(self, width, depth, height, thickness, loc=(0, 0, 0), segments=8):
        """A round-headed opening: two piers carrying a semicircular head."""
        span = width - thickness * 2.0
        pier = height - span / 2.0
        self.box((thickness, depth, pier), (loc[0] - (width - thickness) / 2.0, loc[1], loc[2] + pier / 2.0))
        self.box((thickness, depth, pier), (loc[0] + (width - thickness) / 2.0, loc[1], loc[2] + pier / 2.0))
        inner = span / 2.0
        length = thickness
        for index in range(segments):
            a0 = math.pi * index / segments
            a1 = math.pi * (index + 1) / segments
            mid = (a0 + a1) / 2.0
            self.box(
                (length, depth, (a1 - a0) * (inner + length)),
                (
                    loc[0] + math.cos(mid) * (inner + length / 2.0),
                    loc[1],
                    loc[2] + pier + math.sin(mid) * (inner + length / 2.0),
                ),
                (0.0, -mid, 0.0),
            )
        return self

    def _polyhedron(self, verts, faces, loc, rot):
        matrix = _matrix(loc, (1, 1, 1), rot)
        made = [self.bm.verts.new(matrix @ Vector(v)) for v in verts]
        for face in faces:
            try:
                self.bm.faces.new([made[i] for i in face])
            except ValueError:
                pass
        self.bm.verts.index_update()

    def repeat(self, count, step, fn):
        """Runs `fn(index, offset)` `count` times, stepping `step` between each — colonnades and bays."""
        span = (count - 1) * step / 2.0 if count > 1 else 0.0
        for index in range(count):
            fn(index, index * step - span)
        return self

    def build(self, name, bevel=0.0):
        bmesh.ops.remove_doubles(self.bm, verts=list(self.bm.verts), dist=1e-5)
        if bevel > 0.0:
            bmesh.ops.bevel(
                self.bm,
                geom=list(self.bm.verts) + list(self.bm.edges) + list(self.bm.faces),
                offset=bevel,
                offset_type="OFFSET",
                segments=1,
                profile=0.5,
                affect="EDGES",
                clamp_overlap=True,
            )
        bmesh.ops.recalc_face_normals(self.bm, faces=list(self.bm.faces))
        mesh = bpy.data.meshes.new(name)
        self.bm.to_mesh(mesh)
        self.bm.free()
        obj = bpy.data.objects.new(name, mesh)
        bpy.context.scene.collection.objects.link(obj)
        return obj


class Asset:
    """One named asset: a bag of `Part`s, one per material role."""

    def __init__(self, name):
        self.name = name
        self.parts = {}

    def __getattr__(self, role):
        if role not in ROLES:
            raise AttributeError(role)
        if role not in self.parts:
            self.parts[role] = Part()
        return self.parts[role]

    def build(self, bevel=0.0):
        return [part.build("%s__%s" % (self.name, role), bevel) for role, part in self.parts.items()]


def clear_scene():
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    for mesh in list(bpy.data.meshes):
        bpy.data.meshes.remove(mesh, do_unlink=True)


# --------------------------------------------------------------------------------------------------
# Civic landmarks
#
# Six silhouettes that have to be told apart at a glance from a shallow overhead camera, which is why
# each one commits to a different roofline: a gantry, a pediment, a saw-tooth, cooling drums, a ridge of
# vaults, and a drum tower. Built normalised to a plot radius of 1.
# --------------------------------------------------------------------------------------------------

def apron(asset, lip=0.055, height=0.05):
    """The kerbed plot every facility stands on, so its ground reads as civic rather than as spill."""
    asset.body.box((2.0, 2.0, height), (0.0, 0.0, height / 2.0))
    for sign in (-1.0, 1.0):
        asset.trim.box((2.0, lip, height * 1.9), (0.0, sign * (1.0 - lip / 2.0), height * 0.95))
        asset.trim.box((lip, 2.0, height * 1.9), (sign * (1.0 - lip / 2.0), 0.0, height * 0.95))
    return asset


def scheduler_yard():
    """CPU: a control block and a gantry striding over an open yard on braced legs."""
    a = apron(Asset("cpu"))
    a.body.box((0.62, 0.86, 0.5), (-0.62, -0.42, 0.35))
    a.body.box((0.34, 0.34, 0.86), (-0.62, 0.28, 0.53))
    a.trim.box((0.72, 0.96, 0.05), (-0.62, -0.42, 0.62))
    a.trim.box((0.4, 0.4, 0.05), (-0.62, 0.28, 0.98))
    a.glass.repeat(3, 0.22, lambda i, y: a.glass.box((0.02, 0.16, 0.3), (-0.31, y - 0.42, 0.36)))
    a.glass.box((0.28, 0.02, 0.5), (-0.62, 0.115, 0.62))

    # The gantry: two braced legs each side carrying a deck across the yard.
    for sign in (-1.0, 1.0):
        a.metal.box((0.09, 0.09, 0.78), (0.28, sign * 0.72, 0.44))
        a.metal.box((0.09, 0.09, 0.78), (0.86, sign * 0.72, 0.44))
        a.metal.box((0.66, 0.05, 0.05), (0.57, sign * 0.72, 0.8))
        a.metal.box((0.72, 0.04, 0.04), (0.57, sign * 0.72, 0.5), (0.0, 0.42, 0.0))
    a.metal.box((0.66, 1.5, 0.06), (0.57, 0.0, 0.86))
    a.trim.repeat(4, 0.36, lambda i, y: a.trim.box((0.5, 0.05, 0.04), (0.57, y, 0.9)))

    # Floodlight masts, which give the yard its unmistakable spiky corner.
    for x, y in ((0.9, -0.86), (0.9, 0.86)):
        a.metal.cyl(0.022, 0.03, 0.95, (x, y, 0.52), segments=8)
        a.trim.box((0.14, 0.05, 0.05), (x, y, 1.0))
    return a


def grant_office():
    """Memory: a formal office with a portico, colonnade and pediment — the civic building of the set."""
    a = apron(Asset("memory"))
    a.body.box((1.5, 1.02, 0.72), (0.0, 0.16, 0.46))
    a.body.frustum((1.56, 1.08), (1.5, 1.02), 0.1, (0.0, 0.16, 0.05))
    a.trim.box((1.62, 1.14, 0.06), (0.0, 0.16, 0.85))
    a.trim.box((1.5, 1.02, 0.05), (0.0, 0.16, 0.9))

    # Portico: eight columns, an entablature and a pediment.
    a.trim.box((1.28, 0.44, 0.06), (0.0, -0.52, 0.13))
    a.trim.repeat(
        8, 0.16, lambda i, x: a.trim.cyl(0.032, 0.038, 0.62, (x, -0.52, 0.47), segments=8)
    )
    a.trim.box((1.3, 0.5, 0.08), (0.0, -0.52, 0.82))
    a.trim.wedge(0.5, 1.3, 0.24, (0.0, -0.52, 0.86), (0.0, 0.0, math.pi / 2.0))

    # Windows: two storeys of tall bays, plus a clock face over the door.
    for z in (0.32, 0.62):
        a.glass.repeat(7, 0.19, lambda i, x, z=z: a.glass.box((0.11, 0.02, 0.2), (x, -0.34, z)))
    for sign in (-1.0, 1.0):
        a.glass.repeat(
            3, 0.24, lambda i, y, s=sign: a.glass.box((0.02, 0.13, 0.22), (s * 0.755, y + 0.16, 0.47))
        )
    a.trim.cyl(0.11, 0.11, 0.04, (0.0, -0.75, 0.93), (math.pi / 2.0, 0.0, 0.0), segments=16)
    a.glass.cyl(0.085, 0.085, 0.05, (0.0, -0.762, 0.93), (math.pi / 2.0, 0.0, 0.0), segments=16)
    return a


def io_depot():
    """Storage: a saw-tooth shed with a loading canopy and dock doors — north light, read from above."""
    a = apron(Asset("storage"))
    a.body.box((1.86, 1.2, 0.46), (0.0, 0.28, 0.33))

    # Saw-tooth roof: four deep bays, each a ramp with a glazed riser facing the same way. The teeth are
    # deliberately steep — a shallow saw-tooth flattens into a slab from the app's overhead camera.
    def tooth(index, y):
        a.body.ramp(1.86, 0.3, 0.27, (0.0, y + 0.28, 0.56))
        a.glass.box((1.78, 0.015, 0.24), (0.0, y + 0.43, 0.68))

    a.body.repeat(4, 0.3, tooth)

    # Dock: a cantilevered canopy over four roller doors and a raised platform.
    a.trim.box((1.86, 0.5, 0.05), (0.0, -0.62, 0.62))
    a.trim.repeat(4, 0.5, lambda i, x: a.trim.box((0.05, 0.05, 0.58), (x, -0.83, 0.31)))
    a.body.box((1.86, 0.22, 0.12), (0.0, -0.42, 0.06))
    a.trim.repeat(4, 0.44, lambda i, x: a.trim.box((0.3, 0.02, 0.3), (x, -0.315, 0.27)))
    a.metal.repeat(4, 0.44, lambda i, x: a.metal.box((0.32, 0.05, 0.03), (x, -0.36, 0.44)))

    # Silos on the flank, the depot's tell from a distance.
    for y in (0.36, 0.72):
        a.metal.cyl(0.14, 0.14, 0.62, (1.14, y, 0.36), segments=14)
        a.trim.cyl(0.0, 0.15, 0.1, (1.14, y, 0.72), segments=14)
    return a


def tempdb_works():
    """tempdb: a plant of cooling drums, pipework and a flare stack — the scratch space, always working."""
    a = apron(Asset("tempdb"))
    a.body.box((0.86, 0.78, 0.42), (-0.5, -0.42, 0.31))
    a.trim.box((0.94, 0.86, 0.05), (-0.5, -0.42, 0.55))
    a.glass.repeat(3, 0.2, lambda i, x: a.glass.box((0.13, 0.02, 0.18), (x - 0.5, -0.815, 0.34)))

    # Three cooling drums with waisted profiles and railed crowns.
    for x, y, r in ((0.42, -0.34, 0.3), (0.44, 0.44, 0.24), (-0.34, 0.52, 0.2)):
        a.body.cyl(r * 0.78, r, 0.44, (x, y, 0.32), segments=18)
        a.body.cyl(r * 0.92, r * 0.78, 0.3, (x, y, 0.69), segments=18)
        a.trim.cyl(r * 0.98, r * 0.98, 0.035, (x, y, 0.85), segments=18)
        a.metal.cyl(r * 0.55, r * 0.55, 0.06, (x, y, 0.88), segments=12)

    # Pipe bridge tying the drums back to the control block.
    a.metal.cyl(0.035, 0.035, 0.84, (0.0, -0.34, 0.6), (0.0, math.pi / 2.0, 0.0), segments=10)
    a.metal.cyl(0.035, 0.035, 0.8, (0.05, 0.1, 0.66), (math.pi / 2.0, 0.0, 0.4), segments=10)
    a.metal.repeat(3, 0.3, lambda i, x: a.metal.box((0.04, 0.04, 0.5), (x, -0.34, 0.35)))

    # Flare stack.
    a.metal.cyl(0.045, 0.06, 1.05, (-0.78, 0.62, 0.57), segments=10)
    a.trim.cyl(0.075, 0.06, 0.09, (-0.78, 0.62, 1.13), segments=10)
    return a


def log_yard():
    """Log: one long vaulted shed with a travelling crane — a sequential building for a sequential file."""
    a = apron(Asset("log"))
    a.body.box((1.9, 0.94, 0.34), (0.0, 0.3, 0.27))

    # A ridge of half-round vaults running the length of the shed.
    a.trim.repeat(
        6,
        0.31,
        lambda i, x: a.trim.cyl(
            0.24, 0.24, 0.3, (x, 0.3, 0.46), (0.0, math.pi / 2.0, math.pi / 2.0), segments=14
        ),
    )
    a.glass.repeat(6, 0.31, lambda i, x: a.glass.box((0.2, 0.02, 0.16), (x, -0.175, 0.36)))

    # Travelling crane on rails down the open side of the yard.
    for sign in (-1.0, 1.0):
        a.metal.box((0.05, 0.05, 0.5), (sign * 0.82, -0.62, 0.3))
    a.metal.box((1.74, 0.07, 0.06), (0.0, -0.62, 0.58))
    a.metal.box((0.14, 0.14, 0.16), (-0.3, -0.62, 0.49))
    a.metal.cyl(0.012, 0.012, 0.24, (-0.3, -0.62, 0.32), segments=6)
    a.trim.box((0.2, 0.2, 0.06), (-0.3, -0.62, 0.2))

    # Stacked bays waiting to be written, laid out in a strict sequence.
    def stack(index, x):
        for row in range(3 - (index % 2)):
            a.body.box((0.26, 0.5, 0.09), (x, -0.62, 0.05 + row * 0.1))

    a.body.repeat(4, 0.42, stack)
    return a


def lock_authority():
    """Lock: a gatehouse with a drum tower and a real arch through it — the only way in or out."""
    a = apron(Asset("lock"))
    a.body.box((1.42, 0.72, 0.66), (0.0, 0.3, 0.43))
    a.trim.box((1.5, 0.8, 0.06), (0.0, 0.3, 0.79))
    # Merlons along the two long parapet edges only — running them across the roof reads as corrugation.
    for sign in (-1.0, 1.0):
        a.trim.repeat(
            9, 0.16, lambda i, x, s=sign: a.trim.box((0.09, 0.09, 0.1), (x, 0.3 + s * 0.385, 0.86))
        )

    # The gate itself, cut through the block.
    a.trim.arch(0.44, 0.78, 0.5, 0.07, (0.0, 0.3, 0.1))
    a.metal.box((0.3, 0.03, 0.34), (0.0, -0.06, 0.27))
    a.metal.repeat(5, 0.07, lambda i, x: a.metal.box((0.012, 0.05, 0.34), (x, -0.06, 0.27)))

    # Drum tower: the silhouette that makes this one unmistakable.
    a.body.cyl(0.3, 0.34, 1.06, (-0.72, -0.4, 0.58), segments=20)
    a.trim.cyl(0.38, 0.34, 0.08, (-0.72, -0.4, 1.14), segments=20)
    a.trim.repeat(
        8,
        0.0,
        lambda i, _: a.trim.box(
            (0.09, 0.09, 0.1),
            (
                -0.72 + math.cos(i * math.pi / 4.0) * 0.32,
                -0.4 + math.sin(i * math.pi / 4.0) * 0.32,
                1.22,
            ),
            (0.0, 0.0, i * math.pi / 4.0),
        ),
    )
    a.glass.repeat(3, 0.3, lambda i, z: a.glass.box((0.09, 0.02, 0.18), (-0.72, -0.72, z + 0.55)))

    # Flag mast on the parapet.
    a.metal.cyl(0.014, 0.018, 0.42, (0.6, 0.3, 1.02), segments=6)
    a.trim.box((0.16, 0.01, 0.1), (0.68, 0.3, 1.16))
    return a


LANDMARKS = (scheduler_yard, grant_office, io_depot, tempdb_works, log_yard, lock_authority)


# --------------------------------------------------------------------------------------------------
# Scenery
#
# Built at world scale, where one unit is roughly one metre. None of it is measured; it exists to fill
# the ~47% of blocks the plan deliberately leaves empty, and to give the eye something to judge the
# measured buildings against.
# --------------------------------------------------------------------------------------------------

def tree_broadleaf():
    a = Asset("tree_broadleaf")
    a.trunk.cyl(0.16, 0.26, 3.0, (0.0, 0.0, 1.5), segments=7)
    a.trunk.cyl(0.09, 0.12, 1.3, (0.35, 0.1, 2.9), (0.0, 0.7, 0.4), segments=5)
    for loc, radius, scale in (
        ((0.0, 0.0, 4.5), 1.9, (1.0, 1.0, 0.86)),
        ((0.9, 0.35, 3.9), 1.15, (1.0, 1.0, 0.9)),
        ((-0.7, -0.55, 4.1), 1.25, (1.0, 1.0, 0.88)),
        ((0.15, -0.8, 5.2), 1.05, (1.0, 1.0, 0.9)),
    ):
        a.leaf.sphere(radius, loc, scale, segments=10, rings=6)
    return a


def tree_conifer():
    a = Asset("tree_conifer")
    a.trunk.cyl(0.11, 0.2, 2.0, (0.0, 0.0, 1.0), segments=6)
    for z, radius, height in ((1.4, 1.5, 2.2), (2.7, 1.15, 2.0), (3.9, 0.78, 1.8)):
        a.leaf.cyl(0.0, radius, height, (0.0, 0.0, z + height / 2.0), segments=9)
    return a


def tree_ornamental():
    a = Asset("tree_ornamental")
    a.trunk.cyl(0.1, 0.15, 1.9, (0.0, 0.0, 0.95), segments=6)
    a.leaf.sphere(1.15, (0.0, 0.0, 2.7), (1.0, 1.0, 0.78), segments=10, rings=6)
    a.leaf.sphere(0.68, (0.5, 0.3, 2.2), (1.0, 1.0, 0.8), segments=8, rings=5)
    return a


def shrub():
    a = Asset("shrub")
    for loc, radius in (((0.0, 0.0, 0.5), 0.62), ((0.45, 0.2, 0.38), 0.42), ((-0.35, 0.3, 0.4), 0.45)):
        a.leaf.sphere(radius, loc, (1.0, 1.0, 0.8), segments=8, rings=5)
    return a


def hedge():
    """One metre of hedge; the app repeats it along a boundary."""
    a = Asset("hedge")
    a.leaf.frustum((1.0, 0.8), (1.0, 0.66), 0.95)
    return a


def streetlight():
    a = Asset("streetlight")
    a.metal.cyl(0.05, 0.09, 6.4, (0.0, 0.0, 3.2), segments=8)
    a.metal.cyl(0.05, 0.05, 1.1, (0.5, 0.0, 6.3), (0.0, math.pi / 2.0, 0.0), segments=6)
    a.trim.box((0.62, 0.22, 0.12), (0.95, 0.0, 6.22))
    a.glass.box((0.5, 0.16, 0.04), (0.95, 0.0, 6.14))
    a.trim.cyl(0.2, 0.26, 0.3, (0.0, 0.0, 0.15), segments=8)
    return a


def bench():
    a = Asset("bench")
    for sign in (-1.0, 1.0):
        a.metal.box((0.08, 0.55, 0.42), (sign * 0.72, 0.0, 0.21))
    a.trim.repeat(4, 0.15, lambda i, y: a.trim.box((1.7, 0.11, 0.05), (0.0, y, 0.44)))
    a.trim.repeat(3, 0.15, lambda i, z: a.trim.box((1.7, 0.05, 0.11), (0.0, -0.26, z + 0.66)))
    return a


def kiosk():
    a = Asset("kiosk")
    a.body.box((2.2, 1.8, 2.4), (0.0, 0.0, 1.2))
    a.trim.frustum((2.7, 2.3), (2.2, 1.8), 0.22, (0.0, 0.0, 2.4))
    a.glass.box((1.7, 0.03, 1.1), (0.0, -0.9, 1.5))
    a.glass.box((0.03, 1.3, 1.1), (1.1, 0.1, 1.5))
    a.trim.box((2.3, 0.5, 0.06), (0.0, -1.05, 2.3))
    return a


def bus_shelter():
    a = Asset("bus_shelter")
    for x in (-1.7, 1.7):
        a.metal.box((0.1, 0.1, 2.5), (x, 0.6, 1.25))
    a.trim.box((3.8, 1.5, 0.09), (0.0, 0.2, 2.54))
    a.glass.box((3.6, 0.04, 1.9), (0.0, 0.66, 1.35))
    a.glass.box((0.04, 1.2, 1.9), (1.72, 0.1, 1.35))
    a.trim.box((2.0, 0.4, 0.09), (0.0, 0.4, 0.5))
    return a


def fountain():
    a = Asset("fountain")
    a.trim.cyl(2.6, 2.8, 0.55, (0.0, 0.0, 0.28), segments=24)
    a.water.cyl(2.42, 2.42, 0.06, (0.0, 0.0, 0.5), segments=24)
    a.trim.cyl(0.5, 0.62, 0.9, (0.0, 0.0, 0.9), segments=14)
    a.trim.cyl(1.2, 0.2, 0.16, (0.0, 0.0, 1.42), segments=18)
    a.water.cyl(1.05, 1.05, 0.05, (0.0, 0.0, 1.48), segments=18)
    a.trim.cyl(0.16, 0.22, 0.7, (0.0, 0.0, 1.82), segments=10)
    return a


def pavilion():
    a = Asset("pavilion")
    a.trim.box((6.0, 4.6, 0.3), (0.0, 0.0, 0.15))
    for x in (-2.6, 2.6):
        for y in (-1.9, 1.9):
            a.trim.cyl(0.13, 0.16, 3.0, (x, y, 1.8), segments=8)
    a.trim.box((6.4, 5.0, 0.16), (0.0, 0.0, 3.38))
    a.body.wedge(5.0, 6.4, 0.9, (0.0, 0.0, 3.46), (0.0, 0.0, math.pi / 2.0))
    return a


def parked_car():
    """Decoration. A parked car dresses a car park and says nothing about the database.

    It used to be parked because "a moving vehicle would imply flow, and flow is evidence". Flow is
    still evidence — what changed is that the city now *has* the evidence. A moving vehicle is a
    sampled running request and lives in the vehicle kit below; this one stays parked because it is
    scattered by a block's seed and measures nothing.
    """
    a = Asset("parked_car")
    a.body.frustum((1.82, 4.3), (1.74, 4.1), 0.62, (0.0, 0.0, 0.42))
    a.body.frustum((1.66, 2.3), (1.4, 1.75), 0.52, (0.0, -0.2, 1.04))
    a.glass.box((1.5, 0.05, 0.38), (0.0, -1.33, 1.24))
    a.glass.box((1.42, 0.05, 0.34), (0.0, 0.92, 1.24))
    for sign in (-1.0, 1.0):
        a.glass.box((0.04, 1.9, 0.34), (sign * 0.78, -0.2, 1.24))
    for x in (-0.84, 0.84):
        for y in (-1.42, 1.42):
            a.metal.cyl(0.34, 0.34, 0.24, (x, y, 0.34), (0.0, math.pi / 2.0, 0.0), segments=10)
    return a


def rooftop_kit():
    """Plant that lands on flat roofs: two AC units, a water tank, a stair bulkhead and a dish."""
    a = Asset("rooftop")
    a.metal.box((2.0, 1.4, 0.9), (-2.4, 0.6, 0.45))
    a.trim.box((1.8, 1.2, 0.08), (-2.4, 0.6, 0.94))
    a.metal.box((1.5, 1.1, 0.7), (-2.3, -1.5, 0.35))
    a.body.box((1.9, 1.9, 2.4), (2.3, 1.4, 1.2))
    a.trim.box((2.1, 2.1, 0.12), (2.3, 1.4, 2.46))
    for x in (-0.5, 0.5):
        for y in (-0.5, 0.5):
            a.metal.box((0.14, 0.14, 1.5), (2.2 + x, -1.6 + y, 0.75))
    a.metal.cyl(0.95, 0.95, 1.2, (2.2, -1.6, 2.1), segments=14)
    a.trim.cyl(1.05, 0.7, 0.22, (2.2, -1.6, 2.8), segments=14)
    a.metal.cyl(0.06, 0.06, 1.1, (0.0, -2.4, 0.55), segments=6)
    a.trim.cyl(0.0, 0.62, 0.34, (0.0, -2.4, 1.3), (0.5, 0.0, 0.3), segments=14)
    return a


def signal():
    a = Asset("signal")
    a.metal.cyl(0.06, 0.09, 3.6, (0.0, 0.0, 1.8), segments=8)
    a.trim.box((0.26, 0.22, 0.78), (0.0, 0.0, 3.6))
    for z in (3.34, 3.6, 3.86):
        a.glass.box((0.16, 0.03, 0.16), (0.0, -0.12, z))
    return a


def bridge_deck():
    """One metre of bridge, repeated along a crossing: deck and parapets."""
    a = Asset("bridge_deck")
    a.body.box((1.0, 1.0, 0.34), (0.0, 0.0, -0.17))
    for sign in (-1.0, 1.0):
        a.trim.box((1.0, 0.14, 0.5), (0.0, sign * 0.43, 0.25))
        a.trim.box((1.0, 0.2, 0.08), (0.0, sign * 0.43, 0.54))
    return a


SCENERY = (
    tree_broadleaf, tree_conifer, tree_ornamental, shrub, hedge, streetlight, bench, kiosk,
    bus_shelter, fountain, pavilion, parked_car, rooftop_kit, signal, bridge_deck,
)


# --------------------------------------------------------------------------------------------------
# Vehicles
#
# Unlike everything else in this file, these are NOT decoration, and they are exported to their own
# kit for that reason. One of these on a road means a live sampled request was running when the
# sampler last looked, and which of the four it is comes from the estimated bytes that request's plan
# moves. The geometry still measures nothing — the *choice* of which asset to draw is the evidence,
# and that choice is made in `web/src/cityVehicles.ts` from `planDataVolume`.
#
# Keeping them out of `scenery.glb` keeps the one distinction the feature turns on legible: scenery
# is decoration and losing it costs a console line, whereas losing these would silently stop drawing
# live requests, which looks exactly like an idle server.
#
# Every vehicle runs along +Y, is centred on X, and sits on z=0 — the convention `parked_car` already
# uses — so the renderer points one down a road by yawing it and doing nothing else.
#
# The four have to be told apart at a shallow overhead camera at a few pixels tall, and the channel
# that survives that is LENGTH: 1.77m, 4.20m, 6.02m, 12.24m. Height and the cab/box step are
# secondary cues that only pay off when the camera is close.
# --------------------------------------------------------------------------------------------------

def bike():
    """The smallest class. Thin, short and mostly air, so it reads as slight at a glance."""
    a = Asset("vehicle_bike")
    for y in (-0.56, 0.56):
        a.metal.cyl(0.33, 0.33, 0.05, (0.0, y, 0.33), (0.0, math.pi / 2.0, 0.0), segments=12)
    a.body.box((0.07, 1.02, 0.06), (0.0, 0.0, 0.62))
    a.body.box((0.07, 0.06, 0.46), (0.0, -0.36, 0.5), (0.24, 0.0, 0.0))
    a.body.box((0.07, 0.06, 0.5), (0.0, 0.34, 0.46), (-0.3, 0.0, 0.0))
    a.trim.box((0.1, 0.3, 0.07), (0.0, 0.2, 0.94))
    a.metal.box((0.52, 0.06, 0.05), (0.0, -0.5, 0.98))
    return a


def car():
    """A moving car, deliberately the same silhouette as `parked_car`. The only thing separating a
    live query from decoration is that this one moves — which is the honest distinction, because the
    two really are the same object doing different jobs."""
    a = Asset("vehicle_car")
    a.body.frustum((1.78, 4.2), (1.7, 4.0), 0.6, (0.0, 0.0, 0.4))
    a.body.frustum((1.62, 2.24), (1.36, 1.7), 0.5, (0.0, -0.2, 1.0))
    a.glass.box((1.46, 0.05, 0.36), (0.0, -1.3, 1.2))
    a.glass.box((1.38, 0.05, 0.32), (0.0, 0.9, 1.2))
    for sign in (-1.0, 1.0):
        a.glass.box((0.04, 1.86, 0.32), (sign * 0.76, -0.2, 1.2))
    for x in (-0.82, 0.82):
        for y in (-1.38, 1.38):
            a.metal.cyl(0.33, 0.33, 0.23, (x, y, 0.33), (0.0, math.pi / 2.0, 0.0), segments=10)
    return a


def van():
    """A box van: a low cab with a tall square box behind it. The step between the two is the cue
    that separates it from a car when the camera is looking straight down and length is foreshortened."""
    a = Asset("vehicle_van")
    a.body.frustum((2.14, 1.9), (2.02, 1.78), 1.42, (0.0, -2.02, 0.42))
    a.body.box((2.24, 4.3, 2.16), (0.0, 0.86, 1.36))
    a.trim.box((2.3, 0.14, 2.22), (0.0, -1.24, 1.36))
    a.trim.box((2.28, 0.1, 0.16), (0.0, 3.0, 1.9))
    a.glass.box((1.86, 0.05, 0.6), (0.0, -2.94, 1.5))
    for sign in (-1.0, 1.0):
        a.glass.box((0.04, 1.0, 0.5), (sign * 0.98, -2.36, 1.46))
    for x in (-1.0, 1.0):
        for y in (-2.24, 1.5):
            a.metal.cyl(0.44, 0.44, 0.3, (x, y, 0.44), (0.0, math.pi / 2.0, 0.0), segments=10)
    return a


def semi_truck():
    """The largest class: a tractor and a long trailer with a visible break between them. Length
    alone carries the class at map scale, so the articulation gap is kept wide enough to survive
    being a few pixels tall."""
    a = Asset("vehicle_semi_truck")
    a.body.frustum((2.42, 2.5), (2.3, 2.34), 2.5, (0.0, -5.0, 0.62))
    a.trim.box((2.46, 0.16, 2.5), (0.0, -3.78, 1.87))
    a.glass.box((2.06, 0.05, 0.74), (0.0, -6.2, 2.32))
    for sign in (-1.0, 1.0):
        a.glass.box((0.04, 1.2, 0.62), (sign * 1.12, -5.4, 2.26))
    a.metal.box((1.5, 1.1, 0.34), (0.0, -3.3, 1.06))
    a.body.box((2.5, 8.6, 2.72), (0.0, 1.4, 1.86))
    a.trim.box((2.56, 0.12, 2.78), (0.0, 5.64, 1.86))
    for sign in (-1.0, 1.0):
        a.trim.box((0.08, 8.4, 0.14), (sign * 1.27, 1.4, 3.16))
    for x in (-1.06, 1.06):
        for y in (-6.02, -3.44, 3.6, 4.72):
            a.metal.cyl(0.52, 0.52, 0.34, (x, y, 0.52), (0.0, math.pi / 2.0, 0.0), segments=10)
    return a


VEHICLES = (bike, car, van, semi_truck)


# --------------------------------------------------------------------------------------------------
# Export
# --------------------------------------------------------------------------------------------------

def export(objects, path):
    for obj in bpy.data.objects:
        obj.select_set(False)
    for obj in objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_yup=True,
        export_materials="NONE",
        # Normals are omitted deliberately: every mesh here is flat-shaded hard surface, so three.js
        # derives face normals in the shader and the buffers come out roughly half the size.
        export_normals=False,
        export_texcoords=False,
        export_tangents=False,
        export_cameras=False,
        export_lights=False,
        export_animations=False,
    )
    total = sum(len(obj.data.vertices) for obj in objects)
    return {
        "path": os.path.basename(path),
        "meshes": len(objects),
        "vertices": total,
        "kib": round(os.path.getsize(path) / 1024.0, 1),
    }


def generate(out_dir):
    reports = []
    clear_scene()
    landmarks = []
    for builder in LANDMARKS:
        landmarks.extend(builder().build(bevel=0.008))
    reports.append(export(landmarks, os.path.join(out_dir, "landmarks.glb")))

    clear_scene()
    scenery = []
    for builder in SCENERY:
        scenery.extend(builder().build(bevel=0.02))
    reports.append(export(scenery, os.path.join(out_dir, "scenery.glb")))

    clear_scene()
    vehicles = []
    # A finer bevel than the scenery kit's 0.02: a bike frame member is 0.06m thick, and 0.02 of
    # bevel rounds it away entirely.
    for builder in VEHICLES:
        vehicles.extend(builder().build(bevel=0.015))
    reports.append(export(vehicles, os.path.join(out_dir, "vehicles.glb")))
    return reports


def _default_out_dir():
    here = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
    return os.path.join(os.path.dirname(here), "web", "src", "assets")


if __name__ == "__main__":
    for report in generate(globals().get("SIMCITY_OUT") or _default_out_dir()):
        print(report)
